# Site settings
title: Yineng Xiong
SEOTitle: Yineng Xiong's Blog
header-img: img/404-bg.jpg
email: xiongyineng0322@gmail.com
description: ""
keyword: ""
url: "http://yinengxiong.cn"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username: yinengxiong
zhihu_username: YinengXiong
github_username: YinengXiong
twitter_username:  YinengXiong
facebook_username: YinengXiong



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: yinengxiong

# Duoshuo settings
duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: false      # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id: 150646a35b71caa7438ec53852c39c16
# Google Analytics
ga_track_id: 'UA-103709648-1'            # Format: UA-xxxxxx-xx
ga_domain: yinengxiong.cn



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "野鸡学院"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
friends: [
    {
        title: "Google",
        href: "http://www.google.com"
    },
    #{
    #title: "Tongji University",
    # href: "http://www.tongji.edu.cn"
    #}
]
