# Basic
title: Yineng Xiong
subtitle: Yineng Xiong's personal blog
welcome_message: <a href="https://github.com/onevcat/vno-jekyll" target="_blank">Download the theme</a>
description: YinengXiong's personal blog
creator: <a href="http://onev.cat">@onevcat</a>

url: "http://yinengxiong.cn"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color:

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://project.onevcat.com'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: yinengxiong
    # duoshuo: 
    
# Social
social:
    weibo: yinengxiong
    github: YinengXiong
    twitter: YinengXiong
    mail: xiongyineng0322@gmail.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
